[package]
name = "assignment11"
version = "0.1.0"
authors = ["sonukumar-a11 <sonu.kumar@knoldus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.6"
env_logger = "0.5.12"
